import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Image width={100} height={100} alt="Logo" src="logo.svg"></Image>
          <h1>Handcrafted Haven</h1>
        </header>
        <nav>
          <ul>
            <li>MENU1</li>
            <li>MENU2</li>
            <li>MENU3</li>
            <li>MENU4</li>
          </ul>
        </nav>
        {children}
        <footer>FOOTER</footer>
      </body>
    </html>
  );
}
